#
# organization wide configuration for release-drafter
#
# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter

name-template: v$RESOLVED_VERSION
tag-template: v$RESOLVED_VERSION
version-template: $COMPLETE

filter-by-commitish: true

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: 💥 Breaking changes
    labels: 
      - breaking

  - title: 🚨 Removed
    labels:
      - removed

  - title: ⚠️ Deprecated
    labels:
      - deprecated

  - title: 🎉 Major features and improvements
    labels:
      - major-enhancement
      - major-rfe

  - title: 🐛 Major bug fixes
    labels:
      - major-bug

  - title: 🚀 New features and improvements
    labels:
      - enhancement
      - feature
      - rfe

  - title: 🐛 Bug Fixes
    labels:
      - bug
      - fix
      - bugfix
      - regression

  - title: 👷 Changes for developers
    labels:
      - developer

  - title: 📝 Documentation updates
    labels:
      - documentation

  - title: 👻 Maintenance
    labels: 
      - chore
      - internal
      - maintenance

  - title: 🔧 Build
    labels:
      - build
      - github_actions

  - title: 🛡️ Security
    labels:
      - security
      - vulnerability

  - title: 🚦 Tests
    labels: 
      - test
      - tests

  # Default label used by Dependabot
  - title: 📦 Dependency updates
    labels:
      - dependencies
    collapse-after: 15

sort-direction: 'ascending'

exclude-contributors:
  - 'dependabot'
  - 'dependabot[bot]'
  - 'GitHub Action'

exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid

change-template: '- $TITLE ([#$NUMBER]($URL)) @$AUTHOR'

template: |
  ## What's Changed

  $CHANGES

  # ❤️ Thanks
  Many thanks for collaboration on this release for: $CONTRIBUTORS

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

#replacers:
#  - search: '/\[(.*)-(\d+)\]*\s*-*\s*/g'
#    replace: '[[$1-$2]](https://issues.apache.org/jira/browse/$1-$2) - '  
