#
# organization wide configuration for release-drafter
#
# Configuration for Release Drafter: https://github.com/toolmantim/release-drafter

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
#version-template: '$MAJOR.$MINOR.$PATCH$PRERELEASE'

filter-by-commitish: true

# Emoji reference: https://gitmoji.carloscuesta.me/
categories:
  - title: 💥 Breaking changes
    when:
      labels: 
        - breaking

  - title: 🚨 Removed
    when:
      labels: 
        - removed

  - title: ⚠️ Deprecated
    when:
      labels: 
        - deprecated

  - title: 🎉 Major features and improvements
    when:
      labels: 
        - major-enhancement
        - major-rfe

  - title: 🐛 Major bug fixes
    when:
      labels: 
        - major-bug

  - title: 🚀 New features and improvements
    when:
      labels: 
        - enhancement
        - feature
        - rfe

  - title: 🐛 Bug Fixes
    when:
      labels: 
        - bug
        - fix
        - bugfix
        - regression

  - title: 👷 Changes for developers
    when:
      labels: 
        - developer

  - title: 📝 Documentation updates
    when:
      labels: 
        - documentation

  - title: 👻 Maintenance
    when:
      labels: 
        - chore
        - internal
        - maintenance

  - title: 🔧 Build
    when:
      labels: 
        - build
        - github_actions

  - title: 🛡️ Security
    when:
      labels: 
        - security
        - vulnerability

  - title: 🚦 Tests
    when:
      labels: 
        - test
        - tests

  # Default label used by Dependabot
  - title: 📦 Dependency updates
    when:
      labels: 
        - dependencies
    collapse-after: 15

  # Label exclusions
  - type: 'pre-exclude'
    when:
      labels:
        - reverted
        - no-changelog
        - skip-changelog
        - invalid

sort-direction: 'ascending'

exclude-contributors:
  - 'dependabot'
  - 'dependabot[bot]'
  - 'GitHub Action'

# exclude-labels deprecated since v7.4.0 => moved to categories
#exclude-labels:
#  - reverted
#  - no-changelog
#  - skip-changelog
#  - invalid

change-template: '- $TITLE ([#$NUMBER]($URL)) @$AUTHOR'

template: |
  ## What's Changed

  $CHANGES

  ## ❤️ Thanks
  Many thanks for collaboration on this release for: $CONTRIBUTORS

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

#replacers:
#  - search: '/\[(.*)-(\d+)\]*\s*-*\s*/g'
#    replace: '[[$1-$2]](https://issues.apache.org/jira/browse/$1-$2) - '  
